### PR TITLE
basic test for healpix plotting

### PR DESCRIPTION
**Pull request by florianziemen**

### CODE REVIEW

**Review by andrewgettelman — APPROVED** [review]
Fine by me. Not sure what exactly this is doing (just verifying it can produce a plot?) But that works. I haven't gotten to learning testing yet....

**Comment by florianziemen** [comment]
Yeah, I was not sure, what to test exactly, so what I went with is (a) that the code for doing a plot does not crash, and that it (b) produces an image that has roughly 80% value in all three color chanels and a standard deviation of 0.3. Good enough to differentiate tas and pr (I tried that), and hopefully also to detect an empty plot, but also a lot of leeway for changes in the exact behavior of the plot library.
I took the numbers from computing them on the image.
`[0.7763714 0.7910534 0.7830375 1.       ] [0.33580524 0.3303048  0.30626348 0.        ]`
Maybe @lkluft has better ideas...

**Comment by florianziemen** [comment]
yepp, this test detects 0 and nan.

**Comment by lkluft** [comment]
At some point you could split this into two tests, one that loads the data and one that just does a plot. But I am perfectly happy with merging as is, just to have a basic test for the environment to start with.

**Review by lkluft — APPROVED** [review]

**Pull request merged**
